services:
  medvault:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: medvault-app
    restart: unless-stopped
    ports:
      - "5173:80"
    # Agar .env file banayi ho toh un-comment kar sakte hain:
    # env_file:
    #   - .env
